export const services = [
  {
    slug: 'cctv-installation',
    name: 'CCTV Installation',
    nameTa: 'சிசிடிவி நிறுவல்',
    icon: '📷',
    color: 'blue',
    shortDesc: 'Professional HD CCTV systems for homes, shops, offices and industrial units.',
    shortDescTa: 'வீடுகள், கடைகள், அலுவலகங்களுக்கு தொழில்முறை HD கேமரா அமைப்பு.',
    heroDesc: 'Complete CCTV surveillance solutions for 24/7 security monitoring across Tamil Nadu.',
    features: ['HD & 4K Cameras', 'Night Vision up to 40m', 'Remote Mobile Viewing', 'DVR/NVR Setup', 'Motion Alerts', '1-Year Warranty'],
    process: ['Free Site Survey', 'Custom Camera Plan', 'Professional Installation', 'App Setup & Training', '24/7 Support'],
    startingPrice: '₹8,500',
  },
  {
    slug: 'security-camera',
    name: 'Security Camera',
    nameTa: 'பாதுகாப்பு கேமரா',
    icon: '🎥',
    color: 'indigo',
    shortDesc: 'AI-powered indoor & outdoor cameras with smart motion detection.',
    shortDescTa: 'AI தொழில்நுட்பத்துடன் கூடிய உள்/வெளி பாதுகாப்பு கேமராக்கள்.',
    heroDesc: 'Smart security cameras with AI detection, wide-angle coverage and weatherproof design.',
    features: ['AI Motion Detection', '360° Fisheye Options', 'IP67 Weatherproof', 'PTZ Auto-Tracking', '4K Ultra HD', 'Color Night Vision'],
    process: ['Requirement Analysis', 'Camera Selection', 'Professional Mounting', 'App Configuration', 'Demo & Handover'],
    startingPrice: '₹2,200',
  },
  {
    slug: 'security-gate',
    name: 'Security Gate',
    nameTa: 'பாதுகாப்பு கேட்',
    icon: '🚧',
    color: 'green',
    shortDesc: 'Boom barriers, sliding gates & RFID access control systems.',
    shortDescTa: 'தானியங்கி கேட், பூம் பேரியர் மற்றும் RFID அணுகல் அமைப்பு.',
    heroDesc: 'Automated vehicle access control for apartments, offices and industrial facilities.',
    features: ['Boom Barriers 2-3 sec', 'Motorized Sliding Gates', 'RFID Card Access', 'Number Plate Recognition', 'Mobile App Control', 'Battery Backup'],
    process: ['Site Measurement', 'System Design', 'Civil Prep Guidance', 'Installation & Testing', 'Training'],
    startingPrice: '₹15,000',
  },
  {
    slug: 'security-door',
    name: 'Security Door',
    nameTa: 'பாதுகாப்பு கதவு',
    icon: '🚪',
    color: 'purple',
    shortDesc: 'Biometric locks, magnetic doors & digital access control.',
    shortDescTa: 'கைரேகை பூட்டு, காந்த கதவு மற்றும் டிஜிட்டல் அணுகல் கட்டுப்பாடு.',
    heroDesc: 'High-security door systems with biometric access for ultimate entry protection.',
    features: ['Fingerprint + Face ID', '1200 lbs Magnetic Lock', 'RFID Card Access', 'PIN + Multi-factor', 'Glass Door Solutions', 'Access Logs'],
    process: ['Security Assessment', 'Product Selection', 'Professional Install', 'User Enrollment', 'Support Setup'],
    startingPrice: '₹2,800',
  },
  {
    slug: 'intercom-solutions',
    name: 'Intercom Solutions',
    nameTa: 'இன்டர்காம் தீர்வுகள்',
    icon: '📞',
    color: 'cyan',
    shortDesc: 'Video door phones & IP intercom systems for apartments.',
    shortDescTa: 'வீடியோ கதவு போன் மற்றும் அடுக்குமாடி இன்டர்காம் அமைப்பு.',
    heroDesc: 'Complete intercom and video door phone solutions for residential and commercial buildings.',
    features: ['1080P Video Door Phone', 'IP Multi-unit Systems', 'Mobile App Answer', 'Gate Integration', 'Visitor Capture', 'Night Vision'],
    process: ['Building Layout Study', 'System Architecture', 'Structured Cabling', 'Unit Installation', 'Resident Training'],
    startingPrice: '₹4,500',
  },
  {
    slug: 'web-development',
    name: 'Web Development',
    nameTa: 'வலைதள உருவாக்கம்',
    icon: '💻',
    color: 'orange',
    shortDesc: 'Custom websites, e-commerce & web applications.',
    shortDescTa: 'தனிப்பயன் வலைதளங்கள், ஆன்லைன் கடைகள் மற்றும் வலை பயன்பாடுகள்.',
    heroDesc: 'Professional websites and web applications built with modern technology for your business.',
    features: ['Business Websites', 'E-Commerce Stores', 'Custom Web Apps', 'SEO Optimized', 'Mobile Responsive', 'CMS Integration'],
    process: ['Requirement Gathering', 'UI/UX Design', 'Development', 'Testing & QA', 'Launch & Support'],
    startingPrice: '₹8,000',
  },
  {
    slug: 'software-installation',
    name: 'Software Installation',
    nameTa: 'மென்பொருள் நிறுவல்',
    icon: '⚙️',
    color: 'gray',
    shortDesc: 'OS, ERP, antivirus & all business software setup.',
    shortDescTa: 'இயக்க முறைமை, ERP, வைரஸ் தடுப்பு மற்றும் வணிக மென்பொருள் நிறுவல்.',
    heroDesc: 'Professional installation and configuration of all types of software for homes and businesses.',
    features: ['Windows 10/11 Setup', 'Driver Installation', 'Antivirus Config', 'ERP/CRM Setup', 'Office Suite', 'Data Migration'],
    process: ['System Analysis', 'Backup Existing Data', 'Clean Installation', 'Configuration', 'Testing & Handover'],
    startingPrice: '₹500',
  },
  {
    slug: 'billing-software',
    name: 'Billing Software',
    nameTa: 'பில்லிங் மென்பொருள்',
    icon: '🧾',
    color: 'yellow',
    shortDesc: 'GST-compliant POS billing & inventory management.',
    shortDescTa: 'GST இணக்கமான POS பில்லிங் மற்றும் சரக்கு மேலாண்மை.',
    heroDesc: 'Complete billing software with GST invoicing, inventory and business reports for Tamil Nadu businesses.',
    features: ['GST Invoice', 'Barcode POS', 'Inventory Alerts', 'Customer Database', 'Daily Reports', 'SMS Integration'],
    process: ['Business Analysis', 'Software Demo', 'Installation & Config', 'Data Import', 'Staff Training'],
    startingPrice: '₹3,000',
  },
  {
    slug: 'mobile-app',
    name: 'Mobile App Development',
    nameTa: 'மொபைல் பயன்பாடு',
    icon: '📱',
    color: 'pink',
    shortDesc: 'Android & iOS apps from concept to Play Store launch.',
    shortDescTa: 'Android மற்றும் iOS பயன்பாடுகள் — கருத்திலிருந்து Play Store வரை.',
    heroDesc: 'Custom mobile applications for Android and iOS built for your business needs.',
    features: ['Android + iOS Apps', 'Cross-Platform Flutter', 'Beautiful UI/UX', 'Backend API', 'Payment Gateway', 'Play Store Publish'],
    process: ['Discovery & Planning', 'UI/UX Design', 'Development Sprints', 'Testing on Devices', 'Store Submission'],
    startingPrice: '₹25,000',
  },
]

export const colorMap: Record<string, string> = {
  blue: 'bg-blue-50 text-blue-600 border-blue-100',
  indigo: 'bg-indigo-50 text-indigo-600 border-indigo-100',
  green: 'bg-green-50 text-green-600 border-green-100',
  purple: 'bg-purple-50 text-purple-600 border-purple-100',
  cyan: 'bg-cyan-50 text-cyan-600 border-cyan-100',
  orange: 'bg-orange-50 text-orange-600 border-orange-100',
  gray: 'bg-gray-50 text-gray-600 border-gray-100',
  yellow: 'bg-yellow-50 text-yellow-600 border-yellow-100',
  pink: 'bg-pink-50 text-pink-600 border-pink-100',
}
